Lesson 20
dero5001/robot_dreams_tusks pull request #11
Opened 2023-02-13 19:28 UTC by dero5001

Please check my answer

2023-02-16 19:59 UTC, klymenok requested changes

2023-02-16 19:59 UTC, klymenok commented on Lesson_20/Tusk_4.txt
> +    first_name TEXT UNIQUE,
UNIQUE constraint for each field doesn't allow duplicates in these fields. For example, it should be allowed to create records for names `John Snow` and `John Walker`, but your table doesn't allow this.

To fix this, you should use UNIQUE on a table level:
```
...
first_name TEXT,
last_name TEXT,
age INTEGER DEFAULT 18,
UNIQUE(first_name, last_name))

2023-02-19 11:55 UTC, dero5001 commented
Please check now

2023-02-20 21:14 UTC, klymenok approved these changes
Looks good!

2023-02-22 07:19 UTC, merged