Lesson 30
dero5001/robot_dreams_tusks pull request #16
Opened 2023-03-27 19:47 UTC by dero5001

Tusk_1

2023-03-27 20:31 UTC, klymenok requested changes

2023-03-27 20:31 UTC, klymenok commented on Lesson_28/button.js
> +document.getElementById("myButton").onclick = function() {
Файл не відноситься до поточного ДЗ

2023-03-27 20:31 UTC, klymenok commented on Lesson_28/index.html
> +<!DOCTYPE html>
Файл не відноситься до поточного ДЗ

2023-03-27 20:31 UTC, klymenok commented on Lesson_28/styles.css
> +body {
Файл не відноситься до поточного ДЗ

2023-03-27 20:31 UTC, klymenok commented on Lesson_30/Test.py
> +import requests
Файл не відноситься до поточного дз (наскільки я розумію)

2023-03-27 20:31 UTC, klymenok commented on Lesson_30/Tusk_2.py
> +city_name = "Kyiv"
Користувач повинен мати змогу ввести назву містя через input

2023-03-27 20:31 UTC, klymenok commented on Lesson_30/Tusk_2.py
> +#url = f"https://api.open-meteo.com/v1/forecast?latitude={latitude}&longitude={longitude}"
Видаліть непорібні коментарі, або розкоментуйте код, що має бути перевірений

2023-03-28 22:04 UTC, klymenok requested changes

2023-03-28 22:04 UTC, klymenok commented on Lesson_30/Tusk_2.py
> +data = res_geo["results"]
Тут виникне помилка, якщо користувач введе неіснуюче місто

2023-03-29 06:01 UTC, dero5001 commented
Вніс зміни. Перепрошую, за непотрібні файли. Не догледів, що файли з минулого завдання теж запушило в цей пул реквест.

2023-03-30 21:18 UTC, klymenok approved these changes
Looks good!

2023-03-31 07:02 UTC, merged