Lesson 31
dero5001/robot_dreams_tusks pull request #17
Opened 2023-03-29 10:33 UTC by dero5001

Please check

2023-03-30 21:28 UTC, klymenok requested changes

2023-03-30 21:28 UTC, klymenok commented on flask-homework/main.py
> +
Додайте сюди конфігурацію логування, щоб воно запрацівало коректно:

```
dictConfig({
    "version": 1,
    "formatters": {
        "simple": {"format": "%(asctime)s - %(name)s - %(levelname)s - %(message)s"}
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "simple"}
    },
    "root": {"handlers": ["console"], "level": "INFO"},
})
```

2023-03-30 21:28 UTC, klymenok commented on flask-homework/main.py
> +    app.logger.info(print('Hello func was called'))
Приберіть print, тут ви маєте передавати теста, а не результат виконання функції print

2023-03-31 08:07 UTC, dero5001 commented
Дякую. Виправив. 
Не хотів додавати конфігурацію, бо не дуже розумію як це працює.

2023-03-31 19:27 UTC, klymenok approved these changes
Looks good!

2023-04-01 08:54 UTC, merged