Django_3
dero5001/robot_dreams_tusks pull request #22
Opened 2023-04-26 17:33 UTC by dero5001

Please check

2023-04-27 17:34 UTC, klymenok requested changes

2023-04-27 17:34 UTC, klymenok commented on robot_jango_app/purchase/models.py
> +    user = models.ManyToManyField(User)
не потрібно було тут міняти тип звʼязку. В контексті ДЗ достатньо щоб тут був ForeignKey.

2023-05-01 10:27 UTC, klymenok requested changes

2023-05-01 10:27 UTC, klymenok commented on robot_jango_app/purchase/models.py
> +    user = models.ForeignKey(User, related_name='purchases', on_delete=models.CASCADE)
Якщо ви вносите цю зміну, то створіть відповідні міграції

2023-05-01 14:30 UTC, dero5001 commented
Мабуть я щось намудрив з міграціями, бо я самі міграції створив, але мігрувати не міг, видавало помилку. 
Зніс стару базу, створив нову і нові міграції. 

Також стикнувся з проблемою, що pycharm не вважає файли створені django (як то міграції, чи будь які інші файли аплікейшина) як нові і не пушить їх на Git. Мушу вручну це робити.

2023-05-03 11:09 UTC, klymenok commented
> Мабуть я щось намудрив з міграціями, бо я самі міграції створив, але мігрувати не міг, видавало помилку. Зніс стару базу, створив нову і нові міграції.
> 
> Також стикнувся з проблемою, що pycharm не вважає файли створені django (як то міграції, чи будь які інші файли аплікейшина) як нові і не пушить їх на Git. Мушу вручну це робити.

Я б вам рекомендував не користуватися PyCharm взагалі коли мова йде про додавання файлів до комітів і створення комітів. Він може додати щось, що ви б не хотіли бачити на репозиторії

2023-05-03 11:09 UTC, klymenok approved these changes

2023-05-03 15:19 UTC, merged